# Pygame 仿真器配置文件

# 窗口设置
window_width: 1200
window_height: 900
window_title: "RRT-路径规划仿真器"

# 仿真参数
scale: 5  # 像素/米
fps: 60   # 帧率
dt: 0.05  # 仿真时间步长(秒)
lookahead: 6.0  # 路径跟踪前瞻距离

# 车辆参数
vehicle:
  length: 4.5     # 车辆长度(米)
  width: 1.8      # 车辆宽度(米)
  wheelbase: 2.7  # 轴距(米)
  max_speed: 55.0  # 最大速度(m/s)
  max_accel: 10.0   # 最大加速度(m/s^2)
  max_brake: 20.0   # 最大制动(m/s^2)
  max_steer: 0.7854  # 最大转向角(弧度), 约45度 

control_methods:
  pid:
    kp_steer: 2  # 转向控制器的比例增益
    ki_steer: 0.05 # 转向控制器的积分增益
    kd_steer: 4  # 转向控制器的微分增益
    kp_speed: 0.3  # 速度控制器的比例增益
    ki_speed: 2 # 速度控制器的积分增益
    kd_speed: 0.05  # 速度控制器的微分增益
  mpc:
    horizon: 10  # MPC预测时域
    dt: 0.1  # MPC时间步长
    Q: [1.0, 1.0, 0.1]  # 状态权重矩阵
    R: [0.1, 0.1]  # 控制输入权重矩阵
  lqr:
    Q: [1.0, 10.0, 10.0]  # 状态权重矩阵 对应于速度、航向角和转向角速度
    R: [0.1]   # 控制输入权重矩阵 对应于转向角